---
name: Deploy lambda function 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      ZIP_FILE: 'app-${{ github.sha }}.zip'

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Configure AWS credentials
        id: aws-conf
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Create zip
        id: lambda-zip
        run: |
          zip -r $ZIP_FILE ./ --exclude *git*
  
      - name: Install dependency
        run: pip install boto3
  
      - name: Deploy lambda
        id: lambda-deploy
        run: >-
          ansible localhost -m lambda -a 
          "name=helloworld 
           state=present
           zip_file=${ZIP_FILE}
           role='arn:aws:iam::${{ steps.aws-conf.outputs.aws-account-id }}:role/LambdaRole'
           handler='hello.lambda_handler' 
           runtime=python3.8"
  
